### ISSUE TITLE
请问一下，为什么加了cloudera的repository下载还是很慢，有什么加速的方式，已挂代理。

### ISSUE THREAD

**Issue by hanxuanliang** [haichao-zhao/sparksql-train#2]

**Comment by haichao-zhao** [comment]
https://repository.cloudera.com/artifactory/cloudera-repos/这个网址浏览器能正常打开吗？
如果能的话，可以手动下载jar包，不要maven下载，或者你本地开发测试的话，需要的依赖可以不用CDH的版本，用对应版本号的普通版

**Comment by hanxuanliang** [comment]
网站链接是可以打开，但是就是下载jar包很慢。请问一下怎么手动下载jar？对，我是local模式开发。

**Comment by haichao-zhao** [comment]
本地模式的话，你就直接用官方jar包吧，比如你装的是hadoop2.6.0-cdh5.7.0，pom.xml里的依赖版本直接用hadoop2.6.0就可以
例如：
<dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>2.6.0</version>
</dependency>

**Comment by hanxuanliang** [comment]
行，我去试试，thank you
